src/config/routes.rb
# Project name: Arm in Arm Appointment Booker - Team 14
# Description: Allows clients to create/view/delete appointments and admin to manage existing appointments
# Filename: routes.rb
# Description: Defines URL-to-controller mappings for the application
# Last modified on: 4/21/24

# Project Name: Appointment Scheduler and Check-in - team 23
# Description: Add constraints to booking appointments and allow for clients to be checked into their slotted appointments
# FileName: routes.rb
# Description: defines mappings for booking appointments and check in view, also attributes the kaminari implementaitno of pagination
# Last Modified: 4/22/24


# For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

Rails.application.routes.draw do

  resources :locations, except: [:index] do
    get 'locations_page', on: :collection
    patch 'update_location/:id', to: 'locations#update_location', as: 'update_location', on: :collection
    get 'client_view', on: :collection
  end



  #get 'volunteers/upcoming_hours'
  #get 'volunteers/form'
  get 'volunteers/upcoming_hours', to: 'volunteers#upcoming_hours', as: 'upcoming_hours'
  get 'volunteers/form', to: 'volunteers#form', as: 'volunteer_form'
 #post 'volunteers', to: 'volunteers#create'
  get 'admin/schedule_generator', to: 'admin#schedule_generator', as: 'schedule_generator'

  get 'admin/show_schedule', to: 'admin#show_schedule', as: 'show_schedule'

  get 'admin/show_schedule_pdf', to: 'admin#show_schedule_pdf', as: 'show_schedule_pdf'
  post 'volunteers/serverendpoint', to: 'volunteers#create'
  post 'clear_database', to: 'empty_data#clear_database'
  get 'upcoming_hours', to: 'volunteers#upcoming_hours'

  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'

  post 'toggle_dyslexic_font', to: 'application#toggle_dyslexic_font'
  post 'toggle_colorblind', to: 'application#toggle_colorblind'


  get 'appointments/check_in', to: 'appointments#check_in', as:'check_in'
  get 'appointments/search', to: 'appointments#search', as: 'admin_search'
  get 'appointments/search_results', to: 'appointments#search_results', as: 'admin_search_results'



  get 'admin/schedule_generator'
  resources :admin_panels
  get 'new_event',                to: "admin_panels#new"
  get 'main_event_page',          to: "admin_panels#index"
  get 'delete_event',             to: "admin_panels#destroy"
  post 'activate_event',          to: "admin_panels#activate_event"
  post 'de_activate_event',       to: "admin_panels#de_activate_event"



  get '/graphs/nassau', to: 'graphs#nassau'
  get '/graphs/hudson', to: 'graphs#hudson'
  get '/graphs/mobile', to: 'graphs#mobile'


# This is for going into the appointments page
get 'booker/new', to: 'booker#new', as: 'new_appointment'

# This is accessed in the appointments view page
#post 'booking_times', to: 'booker#times', as: 'booker_times'
#get 'booking_times', to: 'booker#times', as: 'booker_times_get'


post 'booker/times', to: 'booker#times', as: 'booker_times'
get 'booker/times', to: redirect('/booker/new')

post 'booker/book', to: 'booker#book', as: 'book_appointment'
post 'booker/update_phone', to: 'booker#update_phone', as: 'update_phone'




  #get 'admin/schedule_generator', to: 'admin#schedule_generator', as: 'schedule_generator'

  #get 'admin/show_schedule', to: 'admin#show_schedule', as: 'show_schedule'

  #get 'admin/show_schedule_pdf', to: 'admin#show_schedule_pdf', as: 'show_schedule_pdf'


  delete 'booker/appointments/:id', to: 'booker#destroy', as: 'delete_appointment'

  resources :members
  resources :households

  # The root page, e.g. www.example.com/, is sent here
  # root 'controller#method_in_controller'

  get '/households', to: 'households#index'
  get 'households/new'
  get '/locations', to: 'locations#locations_page'
  post 'households/sort', to: 'households#sort'
  post 'households_create', to: 'households#create'


 # Team 22 routes used/edited
# Route for household main page
get 'households/index'

# Route for pre-registration form
# get 'households/new'

# Route for sorting the household data
post 'households/sort_asc', to: 'households#sort_asc'
post 'households/sort_desc', to: 'households#sort_desc'

# Used for upload/download feature for households
resources :households do
  # Creates route for download feature
  get 'download', on: :collection, action: :download, as: :download
  
  # Creates upload route for collection of households
  collection do
    post 'upload'
  end
  
  # Connects members resource with households
  resources :members
end

  #route for Pantry Location page
  # get '/locations', to: 'locations#locations_page'
  #route for My Account page

  get 'account/index'
  #route for creating new members for a household
  get 'members/new'
  
  # Devise authentification pages. This controlls the user login


# resources :households do
# get 'download', on: :collection, action: :download, as: :download
#   collection do
#     post 'upload'
#   end
# end

    # Devise authentification pages. This controlls the user login

  # and authentification system.

  get 'statistics/index', as: 'statistics_index'
  # get 'statistics/report_generator', as: 'stat_report_generator', to: 'reports#generate_reports'
  # get '/reports/generate_reports', as: 'stat_report_generator' , to: 'reports#generate_reports'
  get '/reports/generate_reports', as: 'stat_report_generator', to: 'reports#generate_reports'
  post '/reports/generate_reports', to: 'reports#generate_reports'

  post '/reports/generate_reports/getTableData_attendedAppointments', to: 'reports#getTableData_attendedAppointments'
  post '/reports/generate_reports/getTableData_scheduledAppointments', to: 'reports#getTableData_scheduledAppointments'
  post '/reports/generate_reports/getTableData_householdAppointments', to: 'reports#getTableData_householdAppointments'

  post '/reports/generate_reports/download_pdf', to: 'reports#prepare_pdf'
  # post '/reports/generate_reports/delete_pdf', to: 'reports#delete_pdf'

  get 'statistics/graph_generator', as: 'stat_graph_generator'
  post 'statsitics/graph_generator', to: 'graphics#generateGraph', as: 'graph_generation'
  post '/statistics/graph_generator/getBarChartData', to: 'graphics#getBarChartData'
  post '/statistics/graph_generator/getPieChartData', to: 'graphics#getPieChartData'
  post '/statistics/graph_generator/getStackedBarChartData', to: 'graphics#getStackedBarChartData'

  get 'download_pdf' => 'reports#download_pdf'
  get 'download_csv' => 'reports#download_csv'



  get 'statistics/export_report_as_csv', to: 'statistics#export_report_as_csv', as: 'export_report_as_csv'
  get 'statistics/export_report_as_pdf', to: 'statistics#export_report_as_pdf', as: 'export_report_as_pdf'

  get 'statistics/export_graph_as_pdf', to: 'statistics#export_graph_as_pdf', as: 'export_graph_as_pdf'
  # Devise authentification pages. This controlls the user login
  # and authentification system


  # Examples:
  #
  # # Add app CRUD operations from a controller. Used with scaffolding.
  # # CRUD -> create (API/POST), new (page/GET), index, show,
  #           edit(page/GET), update(API/PATCH|PUT), destroy(API/DELETE)
  # resources :my_controller
  #
  # # Add GET path for photos controller, index method
  # get 'photos/index'
  #
  # # Resources, but only register these methods
  # resources :photos, only: [:index, :new, :create, :destroy]
  #resources :volunteers, only: [:new, :create]
  resources :volunteers
  #
  # # Add PUT path for the given url, but send it to a different controller
  # # than rails would assume by the name. to: 'controller#method_name'.
  # # It would have extected to: 'add_tags#add', which would fail
  # put '/add_tags/add', to: 'users#add_tags'


  # Root route
  root 'home#index'

  get "/alert", to: "booker#alert"


  resources :clients, only: [:index, :new, :create, :show, :edit, :update, :destroy]
  # Team 22 routes to sort client data
  post 'clients/sort_asc', to: 'clients#sort_asc'
  post 'clients/sort_desc', to: 'clients#sort_desc'
  resources :new_client, only: [:index]
  resources :my_client, only: [:index]
   resources :search, only: [:index]
  # resources :appointments, only: [:index]


  resources :appointments


  # Devise authentication
  devise_for :users


  # Route the household county drop down menu
  get '/household_county', to: 'households#county_index'

  #team 11 added this
 
  resources :households
  resources :reviews do
    member do
      patch 'approve'
      delete 'deny'
      get 'review'
    end

    
  collection do
    patch :approve_multiple
    delete :deny_multiple
  end
end
end

src/app/models/household.rb
 # Project name: Arm in Arm Project Team 12
 # Description of Project: The Arm in Arm Project aims to develop an application that assits its clients in need of food
 # Filename: household.rb
 # Description: The file defines the Household model, featuring custom validators for household size and head of household age, along with numerous attribute validations and associations with member records
 # Last modified on: April 21, 2024




# app/models/household.rb
# frozen_string_literal: true


# Ensures there aren't too many members in the household
class HouseholdSizeValidator < ActiveModel::Validator
  def validate(record)
    # If any of the fields are nil, we won't add an error here since the presence validations will handle it
    return if record.numadults.nil? || record.numchild.nil?

    # Including the head of the household, the total size should not exceed 7
    if (record.numadults + record.numchild) > 7
      record.errors.add(:base, 'The total number of adults and children must not exceed 7, as the head of the household is already included.')
    end
  end
end

# Ensures the head of household is at least 18 years old
class HeadHouseholdAgeValidator < ActiveModel::Validator
  def validate(record)
    if record.headdob && record.headdob > 18.years.ago
      record.errors.add(:base, 'Must be 18 or older to register.')
    end
  end
end

class Household < ApplicationRecord
  # Validations

  # james: added pantrylocation
  validates :headname, :headdob, :numadults, :numchild, :pantrylocation, :streetaddr, :city, :state, :county, 
            :zipcode, :phonenum, :householdtype, :headgender, :headethnicity, 
            :foodstamps, :incomesource, :qualifiercode, :netincome, presence: true

  validates :headname, format: { with: /\A[a-zA-Z\s-]+\z/, message: 'only allows letters and spaces' }
  validates :numadults, :numchild, numericality: { only_integer: true, greater_than_or_equal_to: 0, less_than_or_equal_to: 7 }
  validates :streetaddr, format: { with: /\A[^\-][a-zA-Z0-9\s,.#'-]+\z/, message: 'contains invalid characters' }
  validates :city, format: { with: /\A[a-zA-Z\s]+\z/, message: 'only allows letters and spaces' }
  validates :zipcode, format: { with: /\A\d{5}(-\d{4})?\z/, message: 'must be a valid ZIP code' }
  validates :phonenum, numericality: { only_integer: true }, length: { is: 10, message: 'must be 10 digits long' }
  validates :netincome, numericality: { greater_than_or_equal_to: 0, message: 'must be non-negative' }
  validates :state, :county, presence: { message: 'must be selected' }
  validates :householdtype, :headgender, :headethnicity, :foodstamps, :incomesource, :qualifiercode, 
            presence: { message: 'must be selected' }

#   validates :headname, :numadults, :numchild, :streetaddr, :city,
#             :zipcode, :phonenum, :netincome, presence: { message: :blank }
#   validates :headdob, :pantrylocation, :state, :county, :householdtype, :headgender, :headethnicity,
#             :foodstamps, :incomesource, :qualifiercode, presence: { message: :selected }

#   validates :headname, :city, format: { with: /\A[a-zA-Z\s-]+\z/, message: :only_letters_and_spaces }
#   validates :numadults, :numchild, :netincome, numericality: { only_integer: true, greater_than_or_equal_to: 0, message: :at_least_zero }
#   validates :streetaddr, format: { with: /\A[^\-][a-zA-Z0-9\s,.#'-]+\z/, message: :invalid_chars }
#   validates :zipcode, format: { with: /\A\d{5}(-\d{4})?\z/, message: :only_numbers }
#   validates :phonenum, format: { with: /\A\d{10}\z/, message: :only_numbers }


  # Custom validators
  validates_with HouseholdSizeValidator, HeadHouseholdAgeValidator

  # Associations
  has_many :members, dependent: :destroy #This makes sure that when a household is deleted, all member records are also deleted
  accepts_nested_attributes_for :members
end

#class Household < ApplicationRecord
    #sets flag to false -- only changed when an issue is caught during registration -- Team13 4/24/24

    # Add validations or associations as needed
    # validates :headname, presence: true
    # validates :headdob, presence: true
    # validates :numadults, presence: true
    # validates :numchild, presence: true
    # validates :pantrylocation, presence: true
    # validates :streetaddr, presence: true
    # validates :city, presence: true
    # validates :state, presence: true
    # validates :county, presence: true
    # validates :zipcode, presence: true
    # validates :phonenum, presence: true
    # validates :householdtype, presence: true
    # validates :headgender, presence: true
    # validates :headethnicity, presence: true
    # validates :foodstamps, presence: true
    # validates :incomesource, presence: true
    # validates :qualifiercode, presence: true
    # validates :netincome, presence: true
#collab14-prototype4
#     validates :headname, presence: true
#     validates :headdob, presence: true
#     validates :numadults, presence: true
#     validates :numchild, presence: true
#     validates :streetaddr, presence: true
#     validates :city, presence: true
#     validates :state, presence: true
#     validates :county, presence: true
#     validates :zipcode, presence: true
#     validates :phonenum, presence: true
#     validates :householdtype, presence: true
#     validates :headgender, presence: true
#     validates :headethnicity, presence: true
#     validates :foodstamps, presence: true
#     validates :incomesource, presence: true
#     validates :qualifiercode, presence: true
#     validates :netincome, presence: true
#     validates :netincome, presence: true

#     # associations
#     has_many :members
#     accepts_nested_attributes_for :members
#   end


# Staging-1
 #   validates :headname, presence: true
  #  validates :headdob, presence: true
   # validates :numadults, presence: true
    #validates :numchild, presence: true
    #validates :streetaddr, presence: true
    #validates :city, presence: true
    #validates :state, presence: true
    #validates :county, presence: true
    #validates :zipcode, presence: true
    #validates :phonenum, presence: true
    #validates :householdtype, presence: true
    #validates :headgender, presence: true
    #validates :headethnicity, presence: true
    #validates :foodstamps, presence: true
    #validates :incomesource, presence: true
    #validates :qualifiercode, presence: true
    #validates :netincome, presence: true

    # associations
    #has_many :members

    #Team 22: households belongs to user & is optional
   # belongs_to :user, optional: true
    #Team 22: presence of user validated based on value of required user
    #validates_presence_of :user, if: :user_required?

   # private
  
    #Team 22: only users that are associated with household & not an admin require a user
    def user_required?
      !user.nil? && !user.admin?
    end
  

src/app/helpers/households_helper.rb
module HouseholdsHelper
end

src/app/views/households/index.html.erb
<!-- 
 Project Name: Admin Dashboard - Team 22
 Description: Allows admin to view & edit household, client, & location data
 Filename: index.html.erb
 Description: This view creates the homepage for households & lists
   all existing households in a table. It also creates the UI that allows
   admin users to add, edit, view, delete, search, sort, upload, & download 
   household data.
 Last Modified: 4/28/2024
-->

<!-- Team22: Style used for this page -->
<style>
  a:visited {
    color: blue !important;
  }
  a:hover{
    color: green !important;
  }
  body{
    background-color: #FAFAFA;
  }
  h1{
    text-align: center;
    background-color: turquoise;
  }
  h2{
    text-align: center;
    background-color: cyan;
  }
  h3{
    text-align: center;
    background-color: silver;
  }
  h4{
    text-align: center;
  }
  label {
    font-size: 20px; /* Adjust the font size as needed */
  }
  select {
    font-size: 22px; /* Adjust the font size as needed */
    padding: 4px;
  }
  .custom-file {
    font-size: 22px; /* Adjust the font size as needed */
    width: 500px; /* Optional: Set a fixed width */
  }
  .border-blocks{
    border: 4px solid #505353;
    border-radius: 5px;
    padding: 10px;
  }
  .table-container{
    overflow-x: auto;
    overflow-y: auto;
    margin: 0 auto;
    max-height: 1200px;
  }
  .table-center{
    margin-left: auto; 
    margin-right: auto;
  }
</style>

<!-- Team22: only admins can view page -->
<% if can?(:access, :rails_admin) %> 
  <p id="notice"><%= notice %></p>
  
  <h1 class="border-blocks" style="margin-bottom: -5px; padding-top: 20px;">Households</h1>
  <h4 class="border-blocks" style="background-color: #FCF9F9;">Admin-only page to view, search, sort, download, & update household data.</h4>

  <br>

  <h3 class="border-blocks" style="margin-bottom: -5px; padding-top: 20px;">Upload spreadsheet to update current households</h3> 
  <div class="border-blocks" style="background-color: #FCF9F9;">
    <!-- Team22: heading with specific style applied -->
    <h4>
      <span style="color: red; font-weight: bold;">
        Edits exisiting households only!
      </span>
      Add households below!
    </h4>

    <!-- Team22: admins can upload a csv file to update ONLY exisiting household data -->
    <%= form_tag upload_households_path, multipart: true do %>
      <div class="text-center">
        <%= file_field_tag :file, class: "custom-file"%>
        <%= submit_tag "Upload CSV", class: "btn btn-primary btn-lg"  %>
      </div>
    <% end %>
  </div>

  <br>

  <h3 style="margin-bottom: -4px; padding-top: 20px;", class="border-blocks">Sort table data based on chosen sorting option</h3>
  <div class="border-blocks">
    <!-- Team22: heading with specific style applied -->
    <h4>Sorts table in 
      <span style="color: blue; font-weight: bold;">
        ascending/descending order
      </span>  
      <br>
      based on
      <span style="color: green; font-weight: bold;">
        column name selected
      </span>
    </h4>

    <!-- Team22: Sorts table household data based on column in ascending order -->
    <%= form_tag households_sort_asc_path, method: :post do %>
      <div class="text-center">
        <%= label_tag :sort_by, "Sort By:", style: "font-weight: bold;" %>
        <%= select_tag :sort_by, options_for_select([["Num Adults", "numadults"], ["Num Children", "numchild"], ["Pantry Location", "pantryloc"], ["City", "city"], ["Zipcode", "zip"], ["Household Type", "household"], ["Qualifier Code", "qcode"], ["Income Source", "incomesrc"], ["Food Stamps", "stamps"]]), include_blank: "Select Sorting Option" %>
        <%= button_tag "Sort Ascending Order", class: "btn btn-primary btn-lg mb-2 ml-4"%>
      </div> 
    <% end %>

    <!-- Team22: Sorts table household data based on column in descending order -->
    <%= form_tag households_sort_desc_path, method: :post do %>
      <div class="text-center">
        <%= label_tag :sort_by, "Sort By:", style: "font-weight: bold;" %>
        <%= select_tag :sort_by, options_for_select([["Num Adults", "numadults"], ["Num Children", "numchild"], ["Pantry Location", "pantryloc"], ["City", "city"], ["Zipcode", "zip"], ["Household Type", "household"], ["Qualifier Code", "qcode"], ["Income Source", "incomesrc"], ["Food Stamps", "stamps"]]), include_blank: "Select Sorting Option" %>
        <%= button_tag "Sort Descending Order", class: "btn btn-primary btn-lg mb-2 ml-4"%>
      </div> 
    <% end %>
  </div>

  <br>

  <h3 style="margin-bottom: -4px; padding-top: 20px;", class=" border-blocks">Search Households</h3>
  
  <div class="form-container border-blocks">
    <h4 style="padding-bottom: 20px;">Fill out the form to search for specific household data</h4>
    
    <!-- Team22: Search form to search for data -->
    <%= form_for :households, url: households_path, method: :get do |form| %>
      <div class="row">
        <!-- Team22: First Column/Group of Input -->
        <div class="col-md-5">
          <div class="form-group">
            <div class="grid-item">
              <%= label_tag :gender, "Gender:", style: "font-weight: bold;" %>
              <%= select_tag :gender, options_for_select(["female", "male", "other"]), include_blank: 'Select Gender' %>
            </div>
            <div class="grid-item">
              <%= label_tag :ethnicity, "Ethnicity:", style: "font-weight: bold;" %>
              <%= select_tag :ethnicity, options_for_select(["black", "latino", "white", "asian", "multiracial"]), include_blank: 'Select Ethnicity' %>
            </div>
            <div class="grid-item">
              <%= label_tag :adults, "Num Adults:", style: "font-weight: bold;" %>
              <%= select_tag :adults, options_for_select(["1", "2", "3", "4", "5", "6", "7", "8", "9", "10"]), include_blank: 'Select # Adults' %>
            </div>
            <div class="grid-item">
              <%= label_tag :children, "Num Children:", style: "font-weight: bold;" %>
              <%= select_tag :children, options_for_select(["0", "1", "2", "3", "4", "5", "6", "7", "8", "9", "10"]), include_blank: 'Select # Children' %>
            </div>
          </div>
        </div>

        <!-- Team22: Second Column/Group of Input -->
        <div class="col-md-5">
          <div class="form-group">
            <div class="grid-item">
              <%= label_tag :pantryloc, "Pantry Location:", style: "font-weight: bold;" %>
              <%= select_tag :pantryloc, options_for_select(@locations.map { |location| [location.name, location.name] }), include_blank: 'Select Location' %>
            </div>
            <div class="grid-item">
              <%= label_tag :cityName, "City:", style: "font-weight: bold;" %>
              <%= select_tag :cityName, options_for_select(["Trenton", "Hamilton Township", "Princeton", "Ewing Township", "Lawrence Township", "Hopewell Borough", "Hopewell Township", "Pennington", "West Windsor Township", "East Windsor Township", "Robbinsville Township"]), include_blank: 'Select City' %>
            </div>
            <div class="grid-item">
              <%= label_tag :stateName, "State:", style: "font-weight: bold;" %>
              <%= select_tag :stateName, options_for_select(["New Jersey"], params[:state]), include_blank: 'Select State' %>
            </div>
            <div class="grid-item">
              <%= label_tag :cnty, "County:", style: "font-weight: bold;" %>
              <%= select_tag :cnty, options_for_select(["Mercer"]), include_blank: 'Select County'  %>
            </div>
            <div class="grid-item">
              <%= label_tag :zip, "Zipcode:", style: "font-weight: bold;" %>
              <%= select_tag :zip, options_for_select(["08501", "08502", "08504", "08505", "08510", "08512", "08515", "08520", "08525", "08528", "08530", "08534", "08536", "08540", "08542", "08550", "08551", "08553", "08555", "08560", "08561", "08608", "08609", "08610", "08611", "08618", "08619", "08620", "08628", "08629", "08638", "08641", "08648", "08690", "08691"]), include_blank: 'Select Zipcode' %>
            </div>
          </div>
        </div>

        <!-- Team22: Third Column/Group of Input -->
        <div class="col-md-5">
          <div class="form-group">
            <div class="grid-item">
              <%= label_tag :incomesrc, "Income Src:", style: "font-weight: bold;" %>
              <%= select_tag :incomesrc, options_for_select(["csupport", "employment", "genassist", "ssi", "ssd", "retirement", "tnaf", "unemployment", "none"]), include_blank: 'Select Income Source' %>
            </div>
            <div class="grid-item">
              <%= label_tag :code, "Qualifier Code:", style: "font-weight: bold;" %>
              <%= select_tag :code, options_for_select(["1-TANF", "2-SNAP", "3-SSI", "4-WIC", "5-Medicaid", "6-Income Eligible", "7-Disaster"]), include_blank: 'Select Qualifier Code' %>
            </div>
            <div class="grid-item">
              <%= label_tag :household, "Household Type:", style: "font-weight: bold;" %>
              <%= select_tag :household, options_for_select(["single", "adultonly", "family"]), include_blank: 'Select Houshould Type' %>
            </div>
            <div class="grid-item">
              <%= label_tag :stamps, "Food Stamps:", style: "font-weight: bold;" %>
              <%= select_tag :stamps, options_for_select(["yes", "no"]), include_blank: 'Select if recieve' %>        
            </div>
          </div>      
        </div>
      </div>

      <!-- Team22: button used to submit form -->
      <div>
        <%= submit_tag "Search", class: 'btn btn-primary btn-lg mt-3"' %>
      </div>        
    <% end %>
  </div>

  <br>
  
  <!-- Team22: Reset button to clear search/sort results -->
  <%= button_to "Clear Search/Sort Results", households_path, method: :get, class: "btn btn-secondary btn-lg mt-3" %>

  <br>

  <!-- Team22: Adds a new household -->
  <%= button_to "Add New Household", new_household_path, method: :get, class: "btn btn-primary btn-lg mt-3" %>
  
  <br>

  <!-- Team22: downloads copy of current data -->
  <h3 class="border-blocks">Download data: click <%= link_to "here", download_households_path(format: :csv) %></h3>
  
  <br>

  <!-- Team22: Displays household data in table -->
  <h2 class="border-blocks", style="margin-bottom: -3px;"> List of Households </h3>
  <div class ="text-center">
    <div class ="table-container border-blocks">
      <table class="table table-center">
        <thead>
          <tr>
            <th scope="col">User ID</th>
            <th scope="col">Household ID</th>
            <th scope="col">Head Name</th>
            <th scope="col">Head DOB</th>
            <th scope="col">Gender</th>
            <th scope="col">Ethnicity</th>
            <th scope="col">Num Adults</th>
            <th scope="col">Num Children</th>
            <th scope="col">Pantry Location</th>
            <th scope="col">Street Address</th>
            <th scope="col">City</th>
            <th scope="col">State</th>
            <th scope="col">County</th>
            <th scope="col">Zipcode</th>
            <th scope="col">Phone Number</th>
            <th scope="col">Income Source</th>
            <th scope="col">Qualifer Code</th>
            <th scope="col">Net Income</th>
            <th scope="col">Household Type</th>
            <th scope="col">Food Stamps</th>
            <th scope="col">Actions</th>
          </tr>
        </thead>
        
        <tbody>
          <!-- Team22: only diplays household data if households exist -->
          <% if @households.empty? %>
            <tr>
              <p class= "text-center"><strong>No households found!!</strong></p>
            </tr>
          <% else %>
            <% @households.each do |household| %>
              <tr>
                <td scope="col" style="text-align: center"><%= household.user_id %></td>
                <td scope="col" style="text-align: center"><%= household.id %></td>
                <td scope="col"><%= household.headname %></td>
                <td scope="col"><%= household.headdob %></td>
                <td scope="col"><%= household.headgender %></td>
                <td scope="col"><%= household.headethnicity %></td>
                <td scope="col"><%= household.numadults %></td>
                <td scope="col"><%= household.numchild %></td>
                <td scope="col"><%= household.pantrylocation%></td>
                <td scope="col"><%= household.streetaddr %></td>
                <td scope="col"><%= household.city %></td>
                <td scope="col"><%= household.state %></td>
                <td scope="col"><%= household.county %></td>
                <td scope="col"><%= household.zipcode %></td>
                <td scope="col"><%= household.phonenum %></td>
                <td scope="col"><%= household.incomesource %></td>
                <td scope="col"><%= household.qualifiercode %></td>
                <td scope="col"><%= household.netincome %></td>
                <td scope="col"><%= household.householdtype %></td>
                <td scope="col"><%= household.foodstamps %></td>

                <!-- Team22: links that allow you view, edit, & delete household data or view members in selected household -->
                <td scope="col">
                  <%= link_to 'View', household %>
                  <%= link_to 'Edit', edit_household_path(household) %>
                  <%= link_to 'Delete', household, method: :delete, data: { confirm: 'Are you sure?' } %>
                  <%= link_to 'Members', household_members_path(household.id) %>
                </td>
              </tr>
            <% end %>
          <% end %>
        </tbody>
      </table>
    </div>
  </div>

  <!-- Footer -->
  <div id="footer">
      <a>© 2024 Copyright: Household List</a>
  </div>
<%end%>
<%= link_to 'New Household', new_household_path %>