src/config/routes.rb
# Project name: Arm in Arm Appointment Booker - Team 14
# Description: Allows clients to create/view/delete appointments and admin to manage existing appointments
# Filename: routes.rb
# Description: Defines URL-to-controller mappings for the application
# Last modified on: 4/21/24

# Project Name: Appointment Scheduler and Check-in - team 23
# Description: Add constraints to booking appointments and allow for clients to be checked into their slotted appointments
# FileName: routes.rb
# Description: defines mappings for booking appointments and check in view, also attributes the kaminari implementaitno of pagination
# Last Modified: 4/22/24


# For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

Rails.application.routes.draw do

  resources :locations, except: [:index] do
    get 'locations_page', on: :collection
    patch 'update_location/:id', to: 'locations#update_location', as: 'update_location', on: :collection
    get 'client_view', on: :collection
  end



  #get 'volunteers/upcoming_hours'
  #get 'volunteers/form'
  get 'volunteers/upcoming_hours', to: 'volunteers#upcoming_hours', as: 'upcoming_hours'
  get 'volunteers/form', to: 'volunteers#form', as: 'volunteer_form'
 #post 'volunteers', to: 'volunteers#create'
  get 'admin/schedule_generator', to: 'admin#schedule_generator', as: 'schedule_generator'

  get 'admin/show_schedule', to: 'admin#show_schedule', as: 'show_schedule'

  get 'admin/show_schedule_pdf', to: 'admin#show_schedule_pdf', as: 'show_schedule_pdf'
  post 'volunteers/serverendpoint', to: 'volunteers#create'
  post 'clear_database', to: 'empty_data#clear_database'
  get 'upcoming_hours', to: 'volunteers#upcoming_hours'

  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'

  post 'toggle_dyslexic_font', to: 'application#toggle_dyslexic_font'
  post 'toggle_colorblind', to: 'application#toggle_colorblind'


  get 'appointments/check_in', to: 'appointments#check_in', as:'check_in'
  get 'appointments/search', to: 'appointments#search', as: 'admin_search'
  get 'appointments/search_results', to: 'appointments#search_results', as: 'admin_search_results'



  get 'admin/schedule_generator'
  resources :admin_panels
  get 'new_event',                to: "admin_panels#new"
  get 'main_event_page',          to: "admin_panels#index"
  get 'delete_event',             to: "admin_panels#destroy"
  post 'activate_event',          to: "admin_panels#activate_event"
  post 'de_activate_event',       to: "admin_panels#de_activate_event"



  get '/graphs/nassau', to: 'graphs#nassau'
  get '/graphs/hudson', to: 'graphs#hudson'
  get '/graphs/mobile', to: 'graphs#mobile'


# This is for going into the appointments page
get 'booker/new', to: 'booker#new', as: 'new_appointment'

# This is accessed in the appointments view page
#post 'booking_times', to: 'booker#times', as: 'booker_times'
#get 'booking_times', to: 'booker#times', as: 'booker_times_get'


post 'booker/times', to: 'booker#times', as: 'booker_times'
get 'booker/times', to: redirect('/booker/new')

post 'booker/book', to: 'booker#book', as: 'book_appointment'
post 'booker/update_phone', to: 'booker#update_phone', as: 'update_phone'




  #get 'admin/schedule_generator', to: 'admin#schedule_generator', as: 'schedule_generator'

  #get 'admin/show_schedule', to: 'admin#show_schedule', as: 'show_schedule'

  #get 'admin/show_schedule_pdf', to: 'admin#show_schedule_pdf', as: 'show_schedule_pdf'


  delete 'booker/appointments/:id', to: 'booker#destroy', as: 'delete_appointment'

  resources :members
  resources :households

  # The root page, e.g. www.example.com/, is sent here
  # root 'controller#method_in_controller'

  get '/households', to: 'households#index'
  get 'households/new'
  get '/locations', to: 'locations#locations_page'
  post 'households/sort', to: 'households#sort'
  post 'households_create', to: 'households#create'


 # Team 22 routes used/edited
# Route for household main page
get 'households/index'

# Route for pre-registration form
# get 'households/new'

# Route for sorting the household data
post 'households/sort_asc', to: 'households#sort_asc'
post 'households/sort_desc', to: 'households#sort_desc'

# Used for upload/download feature for households
resources :households do
  # Creates route for download feature
  get 'download', on: :collection, action: :download, as: :download
  
  # Creates upload route for collection of households
  collection do
    post 'upload'
  end
  
  # Connects members resource with households
  resources :members
end

  #route for Pantry Location page
  # get '/locations', to: 'locations#locations_page'
  #route for My Account page

  get 'account/index'
  #route for creating new members for a household
  get 'members/new'
  
  # Devise authentification pages. This controlls the user login


# resources :households do
# get 'download', on: :collection, action: :download, as: :download
#   collection do
#     post 'upload'
#   end
# end

    # Devise authentification pages. This controlls the user login

  # and authentification system.

  get 'statistics/index', as: 'statistics_index'
  # get 'statistics/report_generator', as: 'stat_report_generator', to: 'reports#generate_reports'
  # get '/reports/generate_reports', as: 'stat_report_generator' , to: 'reports#generate_reports'
  get '/reports/generate_reports', as: 'stat_report_generator', to: 'reports#generate_reports'
  post '/reports/generate_reports', to: 'reports#generate_reports'

  post '/reports/generate_reports/getTableData_attendedAppointments', to: 'reports#getTableData_attendedAppointments'
  post '/reports/generate_reports/getTableData_scheduledAppointments', to: 'reports#getTableData_scheduledAppointments'
  post '/reports/generate_reports/getTableData_householdAppointments', to: 'reports#getTableData_householdAppointments'

  post '/reports/generate_reports/download_pdf', to: 'reports#prepare_pdf'
  # post '/reports/generate_reports/delete_pdf', to: 'reports#delete_pdf'

  get 'statistics/graph_generator', as: 'stat_graph_generator'
  post 'statsitics/graph_generator', to: 'graphics#generateGraph', as: 'graph_generation'
  post '/statistics/graph_generator/getBarChartData', to: 'graphics#getBarChartData'
  post '/statistics/graph_generator/getPieChartData', to: 'graphics#getPieChartData'
  post '/statistics/graph_generator/getStackedBarChartData', to: 'graphics#getStackedBarChartData'

  get 'download_pdf' => 'reports#download_pdf'
  get 'download_csv' => 'reports#download_csv'



  get 'statistics/export_report_as_csv', to: 'statistics#export_report_as_csv', as: 'export_report_as_csv'
  get 'statistics/export_report_as_pdf', to: 'statistics#export_report_as_pdf', as: 'export_report_as_pdf'

  get 'statistics/export_graph_as_pdf', to: 'statistics#export_graph_as_pdf', as: 'export_graph_as_pdf'
  # Devise authentification pages. This controlls the user login
  # and authentification system


  # Examples:
  #
  # # Add app CRUD operations from a controller. Used with scaffolding.
  # # CRUD -> create (API/POST), new (page/GET), index, show,
  #           edit(page/GET), update(API/PATCH|PUT), destroy(API/DELETE)
  # resources :my_controller
  #
  # # Add GET path for photos controller, index method
  # get 'photos/index'
  #
  # # Resources, but only register these methods
  # resources :photos, only: [:index, :new, :create, :destroy]
  #resources :volunteers, only: [:new, :create]
  resources :volunteers
  #
  # # Add PUT path for the given url, but send it to a different controller
  # # than rails would assume by the name. to: 'controller#method_name'.
  # # It would have extected to: 'add_tags#add', which would fail
  # put '/add_tags/add', to: 'users#add_tags'


  # Root route
  root 'home#index'

  get "/alert", to: "booker#alert"


  resources :clients, only: [:index, :new, :create, :show, :edit, :update, :destroy]
  # Team 22 routes to sort client data
  post 'clients/sort_asc', to: 'clients#sort_asc'
  post 'clients/sort_desc', to: 'clients#sort_desc'
  resources :new_client, only: [:index]
  resources :my_client, only: [:index]
   resources :search, only: [:index]
  # resources :appointments, only: [:index]


  resources :appointments


  # Devise authentication
  devise_for :users


  # Route the household county drop down menu
  get '/household_county', to: 'households#county_index'

  #team 11 added this
 
  resources :households
  resources :reviews do
    member do
      patch 'approve'
      delete 'deny'
      get 'review'
    end

    
  collection do
    patch :approve_multiple
    delete :deny_multiple
  end
end
end

src/app/controllers/home_controller.rb
# frozen_string_literal: true

# Controller for the home page already made for you
class HomeController < ApplicationController
  include HomeHelper


  # No sign in needed to access these pages
  # Overrides ApplicationController's instructions to check for login by default
  skip_before_action :authenticate_user!

  # GET /
  #
  # This method is empty, yet it works?
  # Rails controller methods can be completely empty and work just fine.
  # It's the name of the method matching to a html.erb file that
  # makes the link between the files.
  # Find me @ app/views/home/index.html.erb
  #
  # Also, any local variable made inside this method will also exist
  # in the view to be displayed. Do not look up information within the
  # view itself. Do it here, please!

end

src/app/helpers/home_helper.rb
# frozen_string_literal: true

# Helper methods accessable for views within the home folder
module HomeHelper

    # check is user is registered, return true/false
  def check_registered_or_admin()

    # if no one is logged in, return nothing
    if !current_user.present?
      return
    end



    # is registered or admin then return true, false otherwise
    if (current_user.registered) or (current_user.admin == 1)

      return true

    else
      return false
    end


  end

  def check_registered( )
    # if no one is logged in, return nothing
    if !current_user.present?
      return
    end



    # is registered then return true, false otherwise
    if (current_user.registered)

      return true

    end

    return false

  end


  def check_admin( )
    # if no one is logged in, return nothing
    if !current_user.present?
      return
    end



    # is admin then return true, false otherwise
    if (current_user.admin == 1)

      return true

    end

    return false

  end


end

src/app/views/home/_header.html.erb
<%# Bootstrap js & dependencies %>
    <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>

    <%# Navigation Bar %>
    <nav class="navbar navbar-expand-md fixed-top <%= session[:colorblind] == 'enabled' ? 'navbar-colorblind' : 'navbar-standard' %>">

        
      <%= link_to "Home", root_path, class:"navbar-brand"%>
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent"
      aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarSupportedContent">
        <ul class="navbar-nav mr-auto">
          <li class="nav-item">
            <%= link_to "Pre-Register", households_new_path, class:"nav-link" %>
          </li>
          <li class="nav-item">
          <%= link_to "Members", members_path, class:"nav-link" %>
        </li>
          <% if !can?(:access, :rails_admin) %>
          <li class="nav-item">
            <%= link_to "Appointments", new_appointment_path, class:"nav-link" %>
          </li> 
          <%end%>
          <% if can?(:access, :rails_admin) %>     
          <li class="nav-item">
            <%= link_to "Households List", households_path, class:"nav-link" %>
          </li>
          
          <%# team 11 added this %>
          <li class="nav-item">
            <%= link_to "Review Forms", reviews_path, class:"nav-link" %>
          </li> 
          
          <li class="nav-item dropdown">
        <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
          Volunteer
        </a>
        <div class="dropdown-menu" aria-labelledby="navbarDropdown">
          <%= link_to 'View Upcoming Volunteer Hours', upcoming_hours_path, class: 'dropdown-item' %>
          <%= link_to 'Fill out Volunteer Form', volunteer_form_path, class: 'dropdown-item' %>
          <div class="dropdown-divider"></div>
          <a class="dropdown-item" href="#">And Another</a>
        </div>
      </li>
          <% end %>
          <% if !can?(:access, :rails_admin)%>
          
          <li class="nav-item dropdown">
        <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
          Volunteer
        </a>
        <div class="dropdown-menu" aria-labelledby="navbarDropdown">
          <%= link_to 'View Upcoming Volunteer Hours', upcoming_hours_path, class: 'dropdown-item' %>
          <%= link_to 'Fill out Volunteer Form', volunteer_form_path, class: 'dropdown-item' %>
          <div class="dropdown-divider"></div>
          <a class="dropdown-item" href="#">And Another</a>
        </div>
      </li>
                 
  <%end%>

  
      <% if can?(:access, :rails_admin) %>  
        <li class="nav-item">
          <%= link_to "Statistics", statistics_index_path, class: "nav-link" %>
        </li>
        
        <li class="nav-item dropdown">
          <a class="nav-link dropdown-toggle" href="#" id="adminControl" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
            Admin Control
          </a>
          <div class="dropdown-menu" aria-labelledby="adminControl">
            <%= link_to 'Clients List', clients_path, class: 'dropdown-item' %>
            <%= link_to 'Households List', households_path, class: 'dropdown-item' %>
            <%= link_to 'Edit Pantry Locations', locations_page_locations_path, class: 'dropdown-item' %>
          </div>  
        </li>
      <% end %>
    </ul>
<!-- collab-22-->


          <li class="nav-item dropdown">
            <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
              Accessibility
            </a>
            <div class="dropdown-menu" aria-labelledby="navbarDropdown">
              <%= link_to 'Toggle Colorblind Mode', toggle_colorblind_path, class: "dropdown-item", method: :post %>
              <%= link_to 'Toggle Dyslexic Font', toggle_dyslexic_font_path, class: "dropdown-item", method: :post %>
              <div class="dropdown-divider"></div>
              <a class="dropdown-item" href="#">And Another</a>
             </div>
          </li>
        <li class="nav-item dropdown">
          <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
          View Wait Times
            </a>
            <div class="dropdown-menu" aria-labelledby="navbarDropdown">
              <%= link_to 'Trenton', graphs_hudson_path, class: "dropdown-item" %>
              <%= link_to "Princeton", graphs_nassau_path, class:"dropdown-item" %>
              <a class="dropdown-item" <%= link_to "Mobile Pantry", graphs_mobile_path, class:"nav-link" %></a>

            </div>
          </li>
          <% unless current_user.nil? %>
            <li>
              <span>🌐</span>
              <select class="language-selector text-dark" onchange="changeLanguage(this.value)">
                <option value="en" <%= if current_user&.locale == 'en' then 'selected'.html_safe else '' end %>>
		              English
                </option>
                <option value="es" <%= if current_user&.locale == 'es' then 'selected'.html_safe else '' end %>>
                  Español
                </option>
                <option value="ht" <%= if current_user&.locale == 'ht' then 'selected'.html_safe else '' end %>>
                  Kreyòl Ayisyen
                </option>
              </select>
            </li>
            <li class="nav-item">
            <%= link_to "My Account", account_index_path, class:"nav-link" %>
          </li> 

          <% end %>
        </ul>
        
<!-- collab-22-->    

        <ul class="navbar-nav">
          <%# If user, show account, else sign in #%>
          <% if user_signed_in? %>
            <li class="nav-item dropdown">
              <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true"
                  aria-expanded="false">
                Account
                
              </a>
              
              <%# Change to rails "link_to" for the actual links when implementing #%>
              <%# Make sure to include the css class as shown in the login example #%>
              <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdown">
                <%# The rails administration panel link #%>


                <% if can?(:access, :rails_admin) %><%= link_to 'Rails Admin', rails_admin_path, class: "dropdown-item" %>

                


                <!--if user is on admin account, user will have access to admin panel-->
                <% if current_user.email == 'admin@example.com' %>

                  <%= link_to 'Admin Panel', admin_panels_path, class: "dropdown-item" %>
                <% end %>
                
                <div class="dropdown-divider"></div>
                <% end %>
                <%# Devise requires that the logout command be sent using the 'delete' HTTP verb (method) #%>
                <%= link_to "Logout", destroy_user_session_path, class: "dropdown-item", method: :delete %>
              </div>
            </li>
          <% else %>
            <li class="nav-item">
              <%= button_to "Login", new_user_session_path, class: "btn btn-outline-primary" %>
            </li>
          
          <% end %>
        </ul>
      </div>
      
      <script type="text/javascript">
        function changeLanguage(newLanguage) {
          console.log(newLanguage);
          if (location.search != '') {
	          location.search += '&locale=' + newLanguage;
          } else {
            location.search = '?locale=' + newLanguage;
          }

          return false;
        }

        $(document).ready(function() {
          $('.dropdown-toggle').dropdown();
        });
      </script>
    </nav>

src/app/views/home/_viewHours.html.erb
<center><h1>Welcome! Look below to view your upcoming hours</h1></center>

src/app/views/home/index.html.erb
<%# Team 14: Added translations near the bottom #%>

<%# James: added alert here, not sure if it was deleted when merging %>
<% if flash[:info] %>
  <p class="alert alert-primary"><%= flash[:info] %></p>
<% end %>

<!DOCTYPE html>
<html lang="en">

<head>
  <style>
    body {
      font-family: 'Arial', sans-serif;
      margin: 0;
      padding: 0;
      background-color: #f7f7f7;
    }

    header {
      background-color: #2c3e50;
      color: #ecf0f1;
      text-align: center;
      padding: 1em;
    }

    .container {
      max-width: 1200px;
      margin: 20px auto;
      padding: 20px;
      background-color: #fff;
      box-shadow: 0 0 10px rgba(0, 0, 0, 0.1);
      border-radius: 8px;
    }

    img.logo {
      max-width: 100%;
      height: auto;
      display: block;
      margin: 20px auto;
      border-radius: 8px;
    }

    p {
      font-size: 18px;
      line-height: 1.6;
      color: #333;
    }
  </style>
  <!-- this is to help with the tab title -->
  <title><%= yield(:title) %></title>
</head>

<body>
  <header>
    <h1>Arm In Arm</h1>
  </header>

  <div class="container">
    <img class="logo" src="https://arminarm.org/wp-content/uploads/2016/07/20171012_1153150-e1508772260159.jpg" alt="logo" width="700" height="350">
    
    <p>
      Arm in Arm is a nonprofit organization based in Mercer County, New Jersey. Arm In Arm's mission has historically been to ensure that community members in the Mercer County area have their basic needs met and are empowered to achieve stable and self-sufficient lives.
    </p>
    <img class="logo" src="https://arminarm.org/wp-content/uploads/2016/09/cropped-Web-Logo-with-previous-name_V2-e1474384601787.png" alt="logo" width="500" height="200">
  </div>

  <div class="text-center" style="padding-bottom: 100px">
    <% if can?(:access, :rails_admin) %> 
      <h2 style="color: darkgrey;"><%= get_translation('client_profile_title') %></h2>
    <% end %>
  </div>

  <div class="row">
    <div class="mx-auto">
      <% if not current_user.nil? %>
        <% if current_user.can_create_other_client_profiles? %>
          <a href="/new_client" class="btn btn-primary"><%= get_translation('client_profile_create') %></a>
        <% end %>
        <% if not current_user.client.nil? %>
          <a href="/my_client" class="btn btn-primary"><%= get_translation('client_profile_modify') %></a>

          <!-- Button for appointment portal -->
          <% if check_registered() %>
            <%= link_to 'Appointments', new_appointment_path, class: 'btn btn-primary' %>
          <% end %>
        <% end %>

        <% if current_user.can_search? %>
          <a href="/search" class="btn btn-primary"><%= get_translation('client_profile_search') %></a>
          <% if current_user.email == 'admin@example.com' %>
            <%= link_to 'Admin Panel', admin_panels_path, class: "btn btn-primary" %>
            <%= link_to 'Schedule Generator', schedule_generator_path, class: "btn btn-primary" %>
          <% end %>
        <% end %>
      <% end %>
    </div>
  </div>
</body>
</html>

src/app/views/home/show.html.erb
<h1>Client Report</h1>

<p>
  <strong>First Name:</strong>
  <%= @client.first_name %>
</p>

<p>
  <strong>Last Name:</strong>
  <%= @client.last_name %>
</p>

<!-- Add similar code for other attributes -->

<p>
  <strong>Allergies:</strong>
  <%= @client.allergies.present? ? @client.allergies.join(', ') : 'None' %>
</p>

<p>
  <strong>Dietary Restrictions:</strong>
  <%= @client.restrictions.present? ? @client.restrictions.join(', ') : 'None' %>
</p>