src/config/routes.rb
# Project name: Arm in Arm Appointment Booker - Team 14
# Description: Allows clients to create/view/delete appointments and admin to manage existing appointments
# Filename: routes.rb
# Description: Defines URL-to-controller mappings for the application
# Last modified on: 4/21/24

# Project Name: Appointment Scheduler and Check-in - team 23
# Description: Add constraints to booking appointments and allow for clients to be checked into their slotted appointments
# FileName: routes.rb
# Description: defines mappings for booking appointments and check in view, also attributes the kaminari implementaitno of pagination
# Last Modified: 4/22/24


# For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

Rails.application.routes.draw do

  resources :locations, except: [:index] do
    get 'locations_page', on: :collection
    patch 'update_location/:id', to: 'locations#update_location', as: 'update_location', on: :collection
    get 'client_view', on: :collection
  end



  #get 'volunteers/upcoming_hours'
  #get 'volunteers/form'
  get 'volunteers/upcoming_hours', to: 'volunteers#upcoming_hours', as: 'upcoming_hours'
  get 'volunteers/form', to: 'volunteers#form', as: 'volunteer_form'
 #post 'volunteers', to: 'volunteers#create'
  get 'admin/schedule_generator', to: 'admin#schedule_generator', as: 'schedule_generator'

  get 'admin/show_schedule', to: 'admin#show_schedule', as: 'show_schedule'

  get 'admin/show_schedule_pdf', to: 'admin#show_schedule_pdf', as: 'show_schedule_pdf'
  post 'volunteers/serverendpoint', to: 'volunteers#create'
  post 'clear_database', to: 'empty_data#clear_database'
  get 'upcoming_hours', to: 'volunteers#upcoming_hours'

  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'

  post 'toggle_dyslexic_font', to: 'application#toggle_dyslexic_font'
  post 'toggle_colorblind', to: 'application#toggle_colorblind'


  get 'appointments/check_in', to: 'appointments#check_in', as:'check_in'
  get 'appointments/search', to: 'appointments#search', as: 'admin_search'
  get 'appointments/search_results', to: 'appointments#search_results', as: 'admin_search_results'



  get 'admin/schedule_generator'
  resources :admin_panels
  get 'new_event',                to: "admin_panels#new"
  get 'main_event_page',          to: "admin_panels#index"
  get 'delete_event',             to: "admin_panels#destroy"
  post 'activate_event',          to: "admin_panels#activate_event"
  post 'de_activate_event',       to: "admin_panels#de_activate_event"



  get '/graphs/nassau', to: 'graphs#nassau'
  get '/graphs/hudson', to: 'graphs#hudson'
  get '/graphs/mobile', to: 'graphs#mobile'


# This is for going into the appointments page
get 'booker/new', to: 'booker#new', as: 'new_appointment'

# This is accessed in the appointments view page
#post 'booking_times', to: 'booker#times', as: 'booker_times'
#get 'booking_times', to: 'booker#times', as: 'booker_times_get'


post 'booker/times', to: 'booker#times', as: 'booker_times'
get 'booker/times', to: redirect('/booker/new')

post 'booker/book', to: 'booker#book', as: 'book_appointment'
post 'booker/update_phone', to: 'booker#update_phone', as: 'update_phone'




  #get 'admin/schedule_generator', to: 'admin#schedule_generator', as: 'schedule_generator'

  #get 'admin/show_schedule', to: 'admin#show_schedule', as: 'show_schedule'

  #get 'admin/show_schedule_pdf', to: 'admin#show_schedule_pdf', as: 'show_schedule_pdf'


  delete 'booker/appointments/:id', to: 'booker#destroy', as: 'delete_appointment'

  resources :members
  resources :households

  # The root page, e.g. www.example.com/, is sent here
  # root 'controller#method_in_controller'

  get '/households', to: 'households#index'
  get 'households/new'
  get '/locations', to: 'locations#locations_page'
  post 'households/sort', to: 'households#sort'
  post 'households_create', to: 'households#create'


 # Team 22 routes used/edited
# Route for household main page
get 'households/index'

# Route for pre-registration form
# get 'households/new'

# Route for sorting the household data
post 'households/sort_asc', to: 'households#sort_asc'
post 'households/sort_desc', to: 'households#sort_desc'

# Used for upload/download feature for households
resources :households do
  # Creates route for download feature
  get 'download', on: :collection, action: :download, as: :download
  
  # Creates upload route for collection of households
  collection do
    post 'upload'
  end
  
  # Connects members resource with households
  resources :members
end

  #route for Pantry Location page
  # get '/locations', to: 'locations#locations_page'
  #route for My Account page

  get 'account/index'
  #route for creating new members for a household
  get 'members/new'
  
  # Devise authentification pages. This controlls the user login


# resources :households do
# get 'download', on: :collection, action: :download, as: :download
#   collection do
#     post 'upload'
#   end
# end

    # Devise authentification pages. This controlls the user login

  # and authentification system.

  get 'statistics/index', as: 'statistics_index'
  # get 'statistics/report_generator', as: 'stat_report_generator', to: 'reports#generate_reports'
  # get '/reports/generate_reports', as: 'stat_report_generator' , to: 'reports#generate_reports'
  get '/reports/generate_reports', as: 'stat_report_generator', to: 'reports#generate_reports'
  post '/reports/generate_reports', to: 'reports#generate_reports'

  post '/reports/generate_reports/getTableData_attendedAppointments', to: 'reports#getTableData_attendedAppointments'
  post '/reports/generate_reports/getTableData_scheduledAppointments', to: 'reports#getTableData_scheduledAppointments'
  post '/reports/generate_reports/getTableData_householdAppointments', to: 'reports#getTableData_householdAppointments'

  post '/reports/generate_reports/download_pdf', to: 'reports#prepare_pdf'
  # post '/reports/generate_reports/delete_pdf', to: 'reports#delete_pdf'

  get 'statistics/graph_generator', as: 'stat_graph_generator'
  post 'statsitics/graph_generator', to: 'graphics#generateGraph', as: 'graph_generation'
  post '/statistics/graph_generator/getBarChartData', to: 'graphics#getBarChartData'
  post '/statistics/graph_generator/getPieChartData', to: 'graphics#getPieChartData'
  post '/statistics/graph_generator/getStackedBarChartData', to: 'graphics#getStackedBarChartData'

  get 'download_pdf' => 'reports#download_pdf'
  get 'download_csv' => 'reports#download_csv'



  get 'statistics/export_report_as_csv', to: 'statistics#export_report_as_csv', as: 'export_report_as_csv'
  get 'statistics/export_report_as_pdf', to: 'statistics#export_report_as_pdf', as: 'export_report_as_pdf'

  get 'statistics/export_graph_as_pdf', to: 'statistics#export_graph_as_pdf', as: 'export_graph_as_pdf'
  # Devise authentification pages. This controlls the user login
  # and authentification system


  # Examples:
  #
  # # Add app CRUD operations from a controller. Used with scaffolding.
  # # CRUD -> create (API/POST), new (page/GET), index, show,
  #           edit(page/GET), update(API/PATCH|PUT), destroy(API/DELETE)
  # resources :my_controller
  #
  # # Add GET path for photos controller, index method
  # get 'photos/index'
  #
  # # Resources, but only register these methods
  # resources :photos, only: [:index, :new, :create, :destroy]
  #resources :volunteers, only: [:new, :create]
  resources :volunteers
  #
  # # Add PUT path for the given url, but send it to a different controller
  # # than rails would assume by the name. to: 'controller#method_name'.
  # # It would have extected to: 'add_tags#add', which would fail
  # put '/add_tags/add', to: 'users#add_tags'


  # Root route
  root 'home#index'

  get "/alert", to: "booker#alert"


  resources :clients, only: [:index, :new, :create, :show, :edit, :update, :destroy]
  # Team 22 routes to sort client data
  post 'clients/sort_asc', to: 'clients#sort_asc'
  post 'clients/sort_desc', to: 'clients#sort_desc'
  resources :new_client, only: [:index]
  resources :my_client, only: [:index]
   resources :search, only: [:index]
  # resources :appointments, only: [:index]


  resources :appointments


  # Devise authentication
  devise_for :users


  # Route the household county drop down menu
  get '/household_county', to: 'households#county_index'

  #team 11 added this
 
  resources :households
  resources :reviews do
    member do
      patch 'approve'
      delete 'deny'
      get 'review'
    end

    
  collection do
    patch :approve_multiple
    delete :deny_multiple
  end
end
end

src/app/models/client.rb
class Client < ApplicationRecord

  has_many :appointments
  # has_one :household, through: :user

  # ActiveRecord automatically creates attribute accessors for all the database columns


  # Validations
  validates :first_name, :last_name, :dob, presence: true

  # Custom methods (similar to your original class)

  # def add_allergy(allergy)
  #   self.allergies << allergy
  # end


  # def add_restriction(restriction)
  #   self.restrictions << restriction
  # end

  # Helpful constant containing list of common allergens and their names.
  COMMON_ALLERGENS = [
    [:allergy_peanuts,   "Peanuts"],
    [:allergy_treenuts,  "Tree nuts"],
    [:allergy_eggs,      "Eggs"],
    [:allergy_milk,      "Milk"],
    [:allergy_shellfish, "Shellfish"],
    [:allergy_fish,      "Fish"],
    [:allergy_wheat,     "Wheat"],
    [:allergy_soy,       "Soy"],
  ]

  has_many :users, dependent: :destroy


  # Custom method to derive the age of a client based on their date of birth.
  def age
    # What day is it today?
    today = Date.today
    # The client is at most as old as the difference between the years.
    result = today.year - dob.year
    # If their birthday hasn't yet passed this year, subtract one from the result.
    if today.month < dob.month or (today.month == dob.month and today.day < dob.day)
      result -= 1
    end
    # Return final result.
    result
  end

  # Custom method to create a readable string list of the client's common allergens.
  def allergies_string
    strings = []
    COMMON_ALLERGENS.each do |sym, name|
      # Send method calls a method by name, e.g. self.send :foo is the same as self.foo
      if send sym
        # Team 14: Added translation here. Having to translate here makes it difficult to use the get_translation method
        # defined in app/helpers/application_helper.rb. Using .yml files for now.
        
        # strings.push get_translation("new_client_#{sym}")
        # translation = Translation.where("key = ?", "new_client_#{sym}")[0][current_user&.locale]
        strings.push (I18n.t "new_client.#{sym}")
      end
    end
    # Join to string.
    strings.join ', '
  end
end

src/app/controllers/client_controller.rb
class ClientsController < ApplicationController
    def new
      @client = Client.new
    end
  
    def create
      @client = Client.new(client_params)
      if @client.save
        flash[:notice] = "Client profile created successfully!"
        redirect_to client_path(@client)  # Redirect to the show action
      else
        flash.now[:alert] = "Failed to create client profile."
        render :new
      end
    end
    
    def show
      @client = Client.find(params[:id])
    end
    
  
    private
  
    def client_params
      params.require(:client).permit(
        :first_name, 
        :last_name, 
        :dob, 
        :age, 
        :address, 
        :language, 
        :religion, 
        :allergies, 
        :restrictions
      )
    end
  end
  

src/app/views/clients/client.html.erb
<!-- 
 Project Name: Admin Dashboard - Team 22
 Description: Allows admin to view & edit household, client, & location data
 Filename: client.html.erb
 Description: This view lists client data for a client.
  It also provides several buttons for quick access to other relevant pages.
 Last Modified: 4/28/2024
-->

<br>
<h3>Client Information</h3>
<br>
<%# Team 14: Added 4 translations here #%>

<table>
  <tr>
    <th>ID</th>
    <td><%= @client.id %>
  </tr>
  <tr>
    <th>First Name</th>
    <td><%= @client.first_name %></td>
  </tr>
  <tr>
    <th>Last Name</th>
    <td><%= @client.last_name %></td>
  </tr>
  <tr>
    <th>Date of Birth</th>
    <td><%= @client.dob %></td>
  </tr>
  <tr>
    <th>Address</th>
    <td><%= @client.address %></td>
  </tr>
  <tr>
    <th>Language</th>
    <td><%= @client.language %></td>
  </tr>
  <tr>
    <th>Religion</th>
    <td><%= @client.religion %></td>
  </tr>
  <tr>
    <th>Allergies</th>
    <td><%= @client.allergies_string %></td>
  </tr>
  <tr>
    <th>Gluten-free</th>
    <td><%= if @client.gluten_free then get_translation('prereg_snaps_yes') else get_translation('prereg_snaps_no') end %></td>
  </tr>
  <tr>
    <th>Vegan</th>
    <td><%= if @client.vegan then get_translation('prereg_snaps_yes') else get_translation('prereg_snaps_no') end %></td>
  </tr>
  <tr>
    <th>Dietary Restrictions</th>
    <td><%= @client.restrictions %></td>
  </tr>
</table>

<%= button_to 'Edit', edit_client_path(@client), method: :get, class: 'btn btn-primary' %>

<!-- Team22: adds buttons based on user type -->
<% if can?(:access, :rails_admin) %>
  <!-- Team22: allows admins to delete client & go back to clients main page -->
  <%= button_to 'Delete', client_path(@client), method: :delete, data: { confirm: 'Are you sure?' }, class: 'btn btn-primary' %>
  <%= button_to 'Clients', clients_path, method: :get, class: 'btn btn-primary' %>
<% else %>
  <!-- Team22: allows users to go back to their My Account page -->
  <%= button_to 'Account', account_index_path, method: :get, class: 'btn btn-primary' %>
<%end%>

src/app/views/clients/edit.html.erb
<!-- 
 Project Name: Admin Dashboard - Team 22
 Description: Allows admin to view & edit household, client, & location data
 Filename: edit.html.erb
 Description: This view renders the form to edit current client data
  and provides several buttons for quick access to different pages
 Last Modified: 4/28/2024
-->

<h1>Edit Client Profile</h1>

<%= form_with model: @client, local: true do |form| %>
  <%= label_tag :first_name, "First Name" %>
  <%= text_field_tag :first_name, @client.first_name %><br>

  <%= label_tag :last_name, "Last Name" %>
  <%= text_field_tag :last_name, @client.last_name %><br>

  <%= label_tag :dob, "Date of Birth (mm/dd/yyyy)" %>
  <%= date_field_tag :dob, @client.dob %><br>

  <h2>Allergies</h2>
  <% Client::COMMON_ALLERGENS.each do |allergen, allergen_name| %>
    <%= hidden_field_tag allergen, '0' %>
    <%= check_box_tag allergen, '1', @client.send(allergen) %>
    <%= label_tag allergen, allergen_name %><br>
  <% end %>

  <%= label_tag :address, "Address" %>
  <%= text_field_tag :address, @client.address %><br>

  <%= label_tag :language, "Language" %>
  <%= text_field_tag :language, @client.language %><br>

  <%= label_tag :religion, "Religion" %>
  <%= text_field_tag :religion, @client.religion %><br>

  <%= label_tag :gluten_free, "Gluten-free" %>
  <%= hidden_field_tag :gluten_free, '0' %>
  <%= check_box_tag :gluten_free, '1', @client.gluten_free %><br>

  <%= label_tag :vegan, "Vegan" %>
  <%= hidden_field_tag :vegan, '0' %>
  <%= check_box_tag :vegan, '1', @client.vegan %><br>

  <%= label_tag :restrictions, "Restrictions" %>
  <%= text_field_tag :restrictions, @client.restrictions %><br>

  <%= submit_tag "Save Changes" %>
<% end %>

<br>

<%= button_to 'View', client_path(@client), method: :get, class: 'btn btn-primary' %>

<!-- Team22: adds buttons based on user type -->
<% if can?(:access, :rails_admin) %>
  <!-- Team22: allows amins to go back to the clients home page -->
  <%= button_to 'Clients', clients_path, method: :get, class: 'btn btn-primary' %>
<% else %>
  <!-- Team22: allows users to go back to their My Account page -->
  <%= button_to 'Account', account_index_path, method: :get, class: 'btn btn-primary' %>
<% end %>

src/app/views/clients/index.html.erb
<!-- 
 Project Name: Admin Dashboard - Team 22
 Description: Allows admin to view & edit household, client, & location data
 Filename: index.html.erb
 Description: This view creates the homepage for clients & lists
   all existing clients in a table. It also creates the UI that allows
   admin users to add, edit, view, and sort client data.
 Last Modified: 4/28/2024
-->

<!-- Team22: Style used for this page -->
<style>
  a:visited {
    color: blue !important;
  }
  a:hover{
    color: green !important;
  }
  body{
    background-color: #FAFAFA;
  }
  h1{
    text-align: center;
    background-color: turquoise;
  }
  h2{
    text-align: center;
    background-color: cyan;
  }
  h3{
    text-align: center;
    background-color: silver;
  }
  h4{
    background-color: #FCF9F9; 
    text-align: center;
  }
  label {
    font-size: 20px; /* Adjust the font size as needed */
  }
  select {
    font-size: 22px; /* Adjust the font size as needed */
    padding: 4px;
  }
  .custom-file {
    font-size: 22px; /* Adjust the font size as needed */
    width: 500px; /* Optional: Set a fixed width */
  }
  .border-blocks{
    border: 4px solid #505353;
    border-radius: 5px;
    padding: 10px;
  }
  .table-container{
    overflow-x: auto;
    overflow-y: auto;
    margin: 0 auto;
    max-height: 1200px;
  }
  .table-center{
    margin-left: auto; 
    margin-right: auto;
  }
</style>

<!-- Team22: only admins can view page -->
<% if can?(:access, :rails_admin) %> 
  <p id="notice"><%= notice %></p>

  <h1 class="border-blocks" style="margin-bottom: -5px; padding-top: 20px;">Clients</h1>
  <h4 class="border-blocks">Admin-only page to view client data.</h4>
  
  <br>

  <h3 style="margin-bottom: -4px; padding-top: 20px;", class="border-blocks text-center">Sort table data based on chosen sorting option</h3>
  <div class="border-blocks">
    <!-- Team22: heading with specific style applied -->
    <h4>Sorts table in 
      <span style="color: blue; font-weight: bold;">
        ascending/descending order
      </span>  
      <br>
      based on
      <span style="color: green; font-weight: bold;">
        column name selected
      </span>
    </h4>
    
    <!-- Team22: Sorts table client data based on column in ascedning order -->
    <%= form_tag clients_sort_asc_path, method: :post do %>
      <div class="text-center">
        <%= label_tag :sort_by, "Sort By:", style: "font-weight: bold;" %>
        <%= select_tag :sort_by, options_for_select([["Language", "lang"], ["Religion", "religion"], ["Peanut Allergy", "peanuts"], ["Treenut Allergy", "treenuts"], ["Egg Allergy", "eggs"], ["Milk Allergy", "milk"], ["Shellfish Allergy", "shellfish"], ["Fish Allergy", "fish"], ["Wheat Allergy", "wheat"], ["Soy Allergy", "soy"], ["Gluten-free", "gluten"], ["Vegan", "vegan"], ["Dietary Restrictions", "diet"]]), include_blank: "Select Sorting Method" %>
        <%= button_tag "Sort Ascending Order", class: "btn btn-primary btn-lg mb-2 ml-4"%>
      </div> 
    <% end %>

    <!-- Team22: Sorts table client data based on column in descending order -->
    <%= form_tag clients_sort_desc_path, method: :post do %>
      <div class="text-center">
        <%= label_tag :sort_by, "Sort By:", style: "font-weight: bold;" %>
        <%= select_tag :sort_by, options_for_select([["Language", "lang"], ["Religion", "religion"], ["Peanut Allergy", "peanuts"], ["Treenut Allergy", "treenuts"], ["Egg Allergy", "eggs"], ["Milk Allergy", "milk"], ["Shellfish Allergy", "shellfish"], ["Fish Allergy", "fish"], ["Wheat Allergy", "wheat"], ["Soy Allergy", "soy"], ["Gluten-free", "gluten"], ["Vegan", "vegan"], ["Dietary Restrictions", "diet"]]), include_blank: "Select Sorting Method" %>
        <%= button_tag "Sort Descending Order", class: "btn btn-primary btn-lg mb-2 ml-4"%>
      </div> 
    <% end %>
  </div>


  <br>

  <!-- Team22: Reset button to clear sort results -->
  <%= button_to "Clear Sort Results", clients_path, method: :get, class: "btn btn-secondary btn-lg mt-3" %>

  <br>

  <!-- Team22: Displays client data in table -->
  <h2 class="text-center border-blocks", style="margin-bottom: -4px;"> List of Clients </h3>
  <div class ="text-center border-blocks">
    <div class ="table-container">
      <table class="table table-center">
        <thead>
          <tr>
            <th scope="col">Client ID</th>
            <th scope="col">First Name</th>
            <th scope="col">Last Name</th>
            <th scope="col">DOB</th>
            <th scope="col">Address</th>
            <th scope="col">Language</th>
            <th scope="col">Religion</th>
            <th scope="col">Allergies</th>
            <th scope="col">Gluten-free</th>
            <th scope="col">Vegan</th>
            <th scope="col">Dietary Restrictions</th>
            <th scope="col">Action</th>
          </tr>
        </thead>

        <tbody>
          <!-- Team22: only diplays client data if clients exist -->
          <% if @clients.empty? %>
            <tr>
              <p class = "text-center"><strong>No clients found!!</strong></p>
            </tr>
          <% else %>
            <% @clients.each do |client| %>
              <tr>
                <td scope="col" style="text-align: center"><%= client.id%></td>
                <td scope="col"><%= client.first_name%></td>
                <td scope="col"><%= client.last_name%></td>
                <td scope="col"><%= client.dob%></td>
                <td scope="col"><%= client.address%></td>
                <td scope="col"><%= client.language%></td>
                <td scope="col"><%= client.religion%></td>
                <td scope="col"><%= client.allergies_string%></td>
                <td scope="col"><%= client.gluten_free%></td>
                <td scope="col"><%= client.vegan%></td>
                <td scope="col"><%= client.restrictions%></td>
                
                <!-- Team22: links that allow you view, edit, or delete client data -->
                <td scope="col">
                    <%= link_to 'View', client_path(client) %>
                    <%= link_to 'Edit', edit_client_path(client) %>
                    <%= link_to 'Delete', client_path(client), method: :delete, data: { confirm: 'Are you sure?' } %>
                </td>
              </tr>
            <% end %>
          <% end %>
        </tbody>
      </table>
    </div>
  </div>

  <!-- Team22: Footer -->
  <div id="footer">
      <a>© 2024 Copyright: Household List</a>
  </div>
<%end%>