src/config/routes.rb
# Project name: Arm in Arm Appointment Booker - Team 14
# Description: Allows clients to create/view/delete appointments and admin to manage existing appointments
# Filename: routes.rb
# Description: Defines URL-to-controller mappings for the application
# Last modified on: 4/21/24

# Project Name: Appointment Scheduler and Check-in - team 23
# Description: Add constraints to booking appointments and allow for clients to be checked into their slotted appointments
# FileName: routes.rb
# Description: defines mappings for booking appointments and check in view, also attributes the kaminari implementaitno of pagination
# Last Modified: 4/22/24


# For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

Rails.application.routes.draw do

  resources :locations, except: [:index] do
    get 'locations_page', on: :collection
    patch 'update_location/:id', to: 'locations#update_location', as: 'update_location', on: :collection
    get 'client_view', on: :collection
  end



  #get 'volunteers/upcoming_hours'
  #get 'volunteers/form'
  get 'volunteers/upcoming_hours', to: 'volunteers#upcoming_hours', as: 'upcoming_hours'
  get 'volunteers/form', to: 'volunteers#form', as: 'volunteer_form'
 #post 'volunteers', to: 'volunteers#create'
  get 'admin/schedule_generator', to: 'admin#schedule_generator', as: 'schedule_generator'

  get 'admin/show_schedule', to: 'admin#show_schedule', as: 'show_schedule'

  get 'admin/show_schedule_pdf', to: 'admin#show_schedule_pdf', as: 'show_schedule_pdf'
  post 'volunteers/serverendpoint', to: 'volunteers#create'
  post 'clear_database', to: 'empty_data#clear_database'
  get 'upcoming_hours', to: 'volunteers#upcoming_hours'

  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'

  post 'toggle_dyslexic_font', to: 'application#toggle_dyslexic_font'
  post 'toggle_colorblind', to: 'application#toggle_colorblind'


  get 'appointments/check_in', to: 'appointments#check_in', as:'check_in'
  get 'appointments/search', to: 'appointments#search', as: 'admin_search'
  get 'appointments/search_results', to: 'appointments#search_results', as: 'admin_search_results'



  get 'admin/schedule_generator'
  resources :admin_panels
  get 'new_event',                to: "admin_panels#new"
  get 'main_event_page',          to: "admin_panels#index"
  get 'delete_event',             to: "admin_panels#destroy"
  post 'activate_event',          to: "admin_panels#activate_event"
  post 'de_activate_event',       to: "admin_panels#de_activate_event"



  get '/graphs/nassau', to: 'graphs#nassau'
  get '/graphs/hudson', to: 'graphs#hudson'
  get '/graphs/mobile', to: 'graphs#mobile'


# This is for going into the appointments page
get 'booker/new', to: 'booker#new', as: 'new_appointment'

# This is accessed in the appointments view page
#post 'booking_times', to: 'booker#times', as: 'booker_times'
#get 'booking_times', to: 'booker#times', as: 'booker_times_get'


post 'booker/times', to: 'booker#times', as: 'booker_times'
get 'booker/times', to: redirect('/booker/new')

post 'booker/book', to: 'booker#book', as: 'book_appointment'
post 'booker/update_phone', to: 'booker#update_phone', as: 'update_phone'




  #get 'admin/schedule_generator', to: 'admin#schedule_generator', as: 'schedule_generator'

  #get 'admin/show_schedule', to: 'admin#show_schedule', as: 'show_schedule'

  #get 'admin/show_schedule_pdf', to: 'admin#show_schedule_pdf', as: 'show_schedule_pdf'


  delete 'booker/appointments/:id', to: 'booker#destroy', as: 'delete_appointment'

  resources :members
  resources :households

  # The root page, e.g. www.example.com/, is sent here
  # root 'controller#method_in_controller'

  get '/households', to: 'households#index'
  get 'households/new'
  get '/locations', to: 'locations#locations_page'
  post 'households/sort', to: 'households#sort'
  post 'households_create', to: 'households#create'


 # Team 22 routes used/edited
# Route for household main page
get 'households/index'

# Route for pre-registration form
# get 'households/new'

# Route for sorting the household data
post 'households/sort_asc', to: 'households#sort_asc'
post 'households/sort_desc', to: 'households#sort_desc'

# Used for upload/download feature for households
resources :households do
  # Creates route for download feature
  get 'download', on: :collection, action: :download, as: :download
  
  # Creates upload route for collection of households
  collection do
    post 'upload'
  end
  
  # Connects members resource with households
  resources :members
end

  #route for Pantry Location page
  # get '/locations', to: 'locations#locations_page'
  #route for My Account page

  get 'account/index'
  #route for creating new members for a household
  get 'members/new'
  
  # Devise authentification pages. This controlls the user login


# resources :households do
# get 'download', on: :collection, action: :download, as: :download
#   collection do
#     post 'upload'
#   end
# end

    # Devise authentification pages. This controlls the user login

  # and authentification system.

  get 'statistics/index', as: 'statistics_index'
  # get 'statistics/report_generator', as: 'stat_report_generator', to: 'reports#generate_reports'
  # get '/reports/generate_reports', as: 'stat_report_generator' , to: 'reports#generate_reports'
  get '/reports/generate_reports', as: 'stat_report_generator', to: 'reports#generate_reports'
  post '/reports/generate_reports', to: 'reports#generate_reports'

  post '/reports/generate_reports/getTableData_attendedAppointments', to: 'reports#getTableData_attendedAppointments'
  post '/reports/generate_reports/getTableData_scheduledAppointments', to: 'reports#getTableData_scheduledAppointments'
  post '/reports/generate_reports/getTableData_householdAppointments', to: 'reports#getTableData_householdAppointments'

  post '/reports/generate_reports/download_pdf', to: 'reports#prepare_pdf'
  # post '/reports/generate_reports/delete_pdf', to: 'reports#delete_pdf'

  get 'statistics/graph_generator', as: 'stat_graph_generator'
  post 'statsitics/graph_generator', to: 'graphics#generateGraph', as: 'graph_generation'
  post '/statistics/graph_generator/getBarChartData', to: 'graphics#getBarChartData'
  post '/statistics/graph_generator/getPieChartData', to: 'graphics#getPieChartData'
  post '/statistics/graph_generator/getStackedBarChartData', to: 'graphics#getStackedBarChartData'

  get 'download_pdf' => 'reports#download_pdf'
  get 'download_csv' => 'reports#download_csv'



  get 'statistics/export_report_as_csv', to: 'statistics#export_report_as_csv', as: 'export_report_as_csv'
  get 'statistics/export_report_as_pdf', to: 'statistics#export_report_as_pdf', as: 'export_report_as_pdf'

  get 'statistics/export_graph_as_pdf', to: 'statistics#export_graph_as_pdf', as: 'export_graph_as_pdf'
  # Devise authentification pages. This controlls the user login
  # and authentification system


  # Examples:
  #
  # # Add app CRUD operations from a controller. Used with scaffolding.
  # # CRUD -> create (API/POST), new (page/GET), index, show,
  #           edit(page/GET), update(API/PATCH|PUT), destroy(API/DELETE)
  # resources :my_controller
  #
  # # Add GET path for photos controller, index method
  # get 'photos/index'
  #
  # # Resources, but only register these methods
  # resources :photos, only: [:index, :new, :create, :destroy]
  #resources :volunteers, only: [:new, :create]
  resources :volunteers
  #
  # # Add PUT path for the given url, but send it to a different controller
  # # than rails would assume by the name. to: 'controller#method_name'.
  # # It would have extected to: 'add_tags#add', which would fail
  # put '/add_tags/add', to: 'users#add_tags'


  # Root route
  root 'home#index'

  get "/alert", to: "booker#alert"


  resources :clients, only: [:index, :new, :create, :show, :edit, :update, :destroy]
  # Team 22 routes to sort client data
  post 'clients/sort_asc', to: 'clients#sort_asc'
  post 'clients/sort_desc', to: 'clients#sort_desc'
  resources :new_client, only: [:index]
  resources :my_client, only: [:index]
   resources :search, only: [:index]
  # resources :appointments, only: [:index]


  resources :appointments


  # Devise authentication
  devise_for :users


  # Route the household county drop down menu
  get '/household_county', to: 'households#county_index'

  #team 11 added this
 
  resources :households
  resources :reviews do
    member do
      patch 'approve'
      delete 'deny'
      get 'review'
    end

    
  collection do
    patch :approve_multiple
    delete :deny_multiple
  end
end
end

src/app/models/admin_panel.rb
# Project name: Arm in Arm Appointment Booker - Team 14 / 21
# Description: Model for the admin panel
# Filename: admin_panel.rb
# Description: Admin panel created by teams 14 and 21 to allow the arm in arm staff to interact with the appointment booking process
# Last modified on: 11/29/23


class AdminPanel < ApplicationRecord
    validates :appointment_length, :max_appointment_count, numericality: { only_integer: true, greater_than: 0 }
    validates :check_in_grace_period, numericality: {only_integer: true, greater_than: -1}
    validates :start_time, presence: true
    validates :end_time, presence: true

    has_many :appointments
end

src/app/controllers/admin_panels_controller.rb
# Project name: Arm in Arm Appointment Booker - Team 14 / 21 / ( 23 from Spr 2024 )
# Description: Allows clients to create/view/delete appointments and admin to manage existing appointments
# Filename: admin_panel_controller.rb
# Description: Controller for the admin panel that interacts with the view for the panel to make changes made by teams 14 and 21.
#              I am concerned with the fact that any user can access this resource. One example is by simple going to the URL for the panels page.


# Last modified on: 04/19/2024



class AdminPanelsController < ApplicationController
  before_action :set_admin_panel, only: %i[ show edit update ]

  before_action :check_authority, only: %i[ de_activate_event activate_event index new show edit update destroy create ]

  # GET /admin_panels or /admin_panels.json
  def index
    @admin_panels = AdminPanel.all

    @temp_active_array = @admin_panels.where( event_active: true )
    @temp_de_active_array = @admin_panels.where( event_active: false )

    
  end

  # GET /admin_panels/1 or /admin_panels/1.json
  def show
  end

  # GET /admin_panels/new
  def new
    @admin_panel = AdminPanel.new
  end

  # GET /admin_panels/1/edit
  def edit
  end

  # POST /admin_panels or /admin_panels.json
  def create

    @admin_panel = AdminPanel.new(admin_panel_params)

    # the date formats that I send in are not usually accepted right away
    @admin_panel.update( start_date: params[ :admin_panel ][ :start_date ].to_date( ), end_date: params[ :admin_panel ][ :end_date ].to_date( ), 
                         event_title: params[ :admin_panel ][ :event_title ], location: params[ :admin_panel ][ :location ],
                          check_in_grace_period: params[ :admin_panel ][ :check_in_grace_period ] )


    respond_to do |format|
      if @admin_panel.save
        
        format.html { redirect_to admin_panels_path, notice: "Admin panel was successfully created." }
      else
        format.html { render :new, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /admin_panels/1 or /admin_panels/1.json
  def update

    # the date formats that I send in are not usually accepted right away
    @admin_panel.update( start_date: params[ :admin_panel ][ :start_date ].to_date( ), end_date: params[ :admin_panel ][ :end_date ].to_date( ), 
                         event_title: params[ :admin_panel ][ :event_title ], location: params[ :admin_panel ][ :location ],
                         check_in_grace_period: params[ :admin_panel ][ :check_in_grace_period ] )


    respond_to do |format|
      if @admin_panel.update(admin_panel_params)
        format.html { redirect_to admin_panels_path, notice: "Admin panel was successfully updated."}
        format.json { render :show, status: :ok, location: @admin_panel }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @admin_panel.errors, status: :unprocessable_entity }
      end
    end

    

  end

  # DELETE /admin_panels/1 or /admin_panels/1.json
  def destroy

    # this is gonna be a number value
    the_event_id = params[:event_id]

    # this is for when an event is being removed
    Appointment.where( admin_panels_id: the_event_id ).each do | appointment |

      appointment.destroy( )

    end

    AdminPanel.all.find_by( id: the_event_id ).destroy( )

    # returning to the main admin panels page
    redirect_to main_event_page_path

    
  end


  def activate_event(  )
    # this will get am event to activate

    event = AdminPanel.where( id: (params[:event]) )
    event.update( event_active: true )

    flash[:msg] = 'Event #{ event.event_title } has been Activated'

    # returning to the main admin panels page
    redirect_to main_event_page_path

  end


  def de_activate_event(  )

    # this is to deactivate an event found in the admin panel
    event = AdminPanel.where( id: (params[:event]) )
    event.update( event_active: false )

    flash[:msg] = 'Event #{ event.event_title } has been De-activated'

    # returning to the main admin panels page
    redirect_to main_event_page_path

  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_admin_panel
      @admin_panel = AdminPanel.find(params[:id])
    end

    def check_authority

      if ( current_user.admin == 0)
        # regular users do not have access to the Admins panenl
        redirect_to root_path
      end

    end

    # Only allow a list of trusted parameters through.
    def admin_panel_params
      params.require(:admin_panel).permit(:appointment_length, :max_appointment_count, :start_time, :end_time,:check_in_grace_period, booking_days: [])
    end
end

src/app/helpers/admin_panels_helper.rb
module AdminPanelsHelper

    def prepare_for_temp_arrays( )

        @start = 0
        @end = @start + 2
        @temp_array = [ ]

    end

    def update_start_end

        @start = @start + 3
        @end = @start + 2

    end

    def set_up_temp_array( event_list )

        @temp_array = event_list.to_a()[ @start..@end ]
        # puts( @temp_array.inspect )

        update_start_end( )

    end

    def get_temp_array( )

        return @temp_array

    end


    def reservation_count( event_id )
        # this function is returning the total appoitnments there are so far for an event
        Appointment.where( admin_panels_id: event_id ).count( )

    end


    def send_card( admin_panel_event )
        
        # this is simply to help with passing values through the partials
        @current_event_card = admin_panel_event

    end


    def get_card( )

        return @current_event_card
    end
end

src/app/views/admin_panels/_card_button.html.erb
<% admin_panel = get_card( ) %>


<%= link_to 'Edit', edit_admin_panel_path( admin_panel ), class: "btn btn-primary" %>

<% if admin_panel.event_active %>

    <%= link_to 'De-activate', de_activate_event_path( event: admin_panel ), class: "btn btn-warning", method: :post %>
    <!-- this passes a string -->

<% else %>

<%= link_to 'Activate', activate_event_path( event: admin_panel ), class: "btn btn-warning", method: :post %>

<% end %>


<a href="<%= delete_event_path( event_id: admin_panel.id ) %>" >
    <button type="button" class="btn btn-danger" >
        Delete
    </button>
</a>

src/app/views/admin_panels/_card_image.html.erb
<% admin_panel = get_card( ) %>

<!-- this can be changed to add different pictures -->
<% if admin_panel.event_title.downcase.include?("food") %>

    <%= image_tag("image1.jpg", :alt => "Food boxes", class: "card-img-top") %>

<% else %>

    <%= image_tag("image2.jpg", :alt => "Food boxes", class: "card-img-top") %>

<% end %>

src/app/views/admin_panels/_card_info.html.erb
<% admin_panel = get_card( ) %>


<ul class="list-group list-group-flush">
                
    <li class="list-group-item d-flex justify-content-between align-items-center">
        Appointment Block (minutes):
        <span class="badge badge-pill"><%= admin_panel.appointment_length %></span>
    </li>
    
    <li class="list-group-item d-flex justify-content-between align-items-center">
        Person per Block:
        <span class="badge badge-pill"><%= admin_panel.max_appointment_count %></span>
    </li>
    
    <li class="list-group-item d-flex justify-content-between align-items-center">
        Day(s) of Event:
        <span class="badge badge-pill"><%= admin_panel.booking_days.reject { |day| day == '0' }.join(', ') %></span>
    </li>
    
    <li class="list-group-item d-flex justify-content-between align-items-center">
        Start/End Time:
        <span class="badge badge-pill"><%= admin_panel.start_time.strftime('%I:%M %p') %> - <%= admin_panel.end_time.strftime('%I:%M %p') %></span>
    </li>
    
    <li class="list-group-item d-flex justify-content-between align-items-center">
        Start Date:
        <span class="badge badge-pill"><%= admin_panel.start_date.strftime('%m-%d-%Y') %></span>
    </li>
    
    <li class="list-group-item d-flex justify-content-between align-items-center">
        End Date:
        <span class="badge badge-pill"><%= admin_panel.end_date.strftime('%m-%d-%Y') %></span>
    </li>
    
    <li class="list-group-item d-flex justify-content-between align-items-center">
        Location(s):
        <span class="badge badge-pill"><%= admin_panel.location.reject { |day| day == '0' }.join(', ') %></span>
    </li>
    
    <li class="list-group-item d-flex justify-content-between align-items-center">
        Reservations count:
        <span class="badge badge-pill"><%= reservation_count( admin_panel.id ) %></span>
    </li>

</ul>

src/app/views/admin_panels/_event_card.html.erb
<% get_temp_array( ).each do |admin_panel| %>
    
    <% send_card( admin_panel ) %>

    <div class="card">

        <%= render "card_image" %>


        <div class="card-body">
        
            <h3 class="card-title">
                
                <%= admin_panel.event_title %>

            </h3>

            <%= render "card_info" %>

            <br>

            <%= render "card_button" %>

        </div>
    </div>
    <div></div>

<% end %>

src/app/views/admin_panels/_form.html.erb
<br>

<div class="container">
  <div class="row">
    <div class="col-md-6 mx-auto">
      <%= form_with(model: admin_panel, local: true) do |form| %>
        <% if admin_panel.errors.any? %>
          <div id="error_explanation">
            <h2><%= pluralize(admin_panel.errors.count, "error") %> prohibited this admin_panel from being saved:</h2>
            <ul>
              <% admin_panel.errors.full_messages.each do |message| %>
                <li><%= message %></li>
              <% end %>
            </ul>
          </div>
        <% end %>

          <!-- this is the event title section -->
        <div class="row">
          <div class="col-md-12">
            <div class="field text-center">
              <%= form.label :event_title, "Title of the event" %>
              <%= form.text_field :event_title, class: "form-control", :required => 'required' %>
            </div>
          </div>
        </div>

        <br>

        <div class="row">
          <div class="col-md-12">
            <div class="field text-center">
              <%= form.label :appointment_length, "How long is a time block?" %>
              <%= form.number_field :appointment_length, class: "form-control" %>
            </div>
          </div>
        </div>

        <div class="row">
          <div class="col-md-12">
            <div class="field text-center">
              <%= form.label :max_appointment_count, "Number of appointments per time block" %>
              <%= form.number_field :max_appointment_count, class: "form-control" %>
            </div>
          </div>
        </div>

        
        <div class="row">
          <div class="col-md-12">
            <div class="field text-center">
              <%= form.label :check_in_grace_period, "How many minutes early can a client check-in?" %>
              <%= form.number_field :check_in_grace_period, class: "form-control" %>
            </div>
          </div>
        </div>

        <br>

        <div class="row">
          <div class="col-md-12">
            <div class="field text-center">
              <%= form.label :booking_days, "What days is this event?" %>
              <div class="form-check">
                <% days_of_week = ['Monday', 'Tuesday', 'Wednesday', 'Thursday', 'Friday', 'Saturday', 'Sunday'] %>
                <% days_of_week.each do |day| %>
                  <label class="form-check-label mr-3">
                    <%= form.check_box :booking_days, { multiple: true, class: 'form-check-input', id: "day_#{day.downcase}", checked: @admin_panel.booking_days.include?(day), value: day }, day %>
                    <%= day %> &nbsp;
                  </label>
                <% end %>
              </div>
            </div>
          </div>
        </div>

        <br>

        <div class="row">
          <div class="col-md-6">
            <div class="field text-center">
              <%= form.label :start_time, "Start Time" %>
              <%= form.time_field :start_time, class: "form-control" %>
            </div>
          </div>

          <div class="col-md-6">
            <div class="field text-center">
              <%= form.label :end_time, "End Time" %>
              <%= form.time_field :end_time, class: "form-control" %>
            </div>
          </div>
        </div>


        <div class="row">
          <div class="col-md-6">
            <div class="field text-center">
              <%= form.label :start_time, "Start Date" %>
              <%= form.date_field :start_date, class: "form-control", :required => 'required' %>
            </div>
          </div>


          <div class="col-md-6">
            <div class="field text-center">
              <%= form.label :start_time, "End Date" %>
              <%= form.date_field :end_date, class: "form-control", :required => 'required' %>
            </div>
          </div>

        </div>

        <br>


        <div class="row">
          <div class="col-md-12">
            <div class="field text-center">
              <%= form.label :location, "Where is this event?" %>
              <div class="form-check">
                <% places = ['Trenton', 'Princeton', 'Mobile'] %>
                <% places.each do |city| %>
                  <label class="form-check-label mr-3">
                    <%= form.check_box :location, { multiple: true, class: 'form-check-input', id: "city_#{city.downcase}", checked: @admin_panel.location.include?(city), value: city }, city %>
                    <%= city %> &nbsp;
                  </label>
                <% end %>
              </div>
            </div>
          </div>
        </div>


        <br>

        <div class="row">
          <div class="col-md-12">
            <div class="actions text-center">
              <%= form.submit class: "btn btn-primary" %>
            </div>
          </div>
        </div>
      <% end %>
    </div>
  </div>
</div>

src/app/views/admin_panels/edit.html.erb
<% provide(:title, "Edit Event") %>

<div class="d-flex justify-content-center"> 
    <h1>Editing Admin Panel</h1>
</div>



<%= render 'form', admin_panel: @admin_panel %>

<%#= link_to 'Show', @admin_panel %>
<%= link_to 'Back', admin_panels_path %>

src/app/views/admin_panels/index.html.erb
<p id="notice"><%= notice %></p>
<% provide(:title, "Events Panel") %>

<div class = "d-flex justify-content-center"> 
    <h1 style="color: #007177; margin-top: 20px;">Admin Panel</h1>
</div>

<br>




<% if @admin_panels.any? %>

  <%= link_to 'Create New Event', new_event_path, class: "btn btn-primary btn-lg" %>
  <br>

  
  <h2 style="color: #007177; margin-top: 20px;">Active Events</h2>
  <div class="dropdown-divider"></div>
  <br>

  <% prepare_for_temp_arrays( ) %>

  <% for i in 0..( @temp_active_array.length( ) / 3 ) do %>

    <% set_up_temp_array( @temp_active_array ) %>
    <div class="card-deck">
      
      <%= render"event_card" %>

    </div>

    <br>

  <% end %>

  
  <br>
  <br>
  <br>

  
  <h2 style="color: #007177; margin-top: 20px;">Past Events</h2>
  <div class="dropdown-divider"></div>
  <br>

  <% prepare_for_temp_arrays( ) %>

  <% for i in 0..( @temp_de_active_array.length( ) / 3 ) do %>

    <% set_up_temp_array( @temp_de_active_array ) %>
    <div class="card-deck">
      
      <%= render"event_card" %>

    </div>

    <br>

  <% end %>






<% else %>

  <div class="alert alert-danger" role="alert">
    
    There are no events available so far

  </div>
  <%= link_to 'Create New Event', new_event_path, class: "btn btn-primary btn-lg" %>




<% end %>


<br>

src/app/views/admin_panels/new.html.erb
<% provide(:title, "New Event") %>

<div class= "d-flex justify-content-center"> 

    <h1>New Admin Panel</h1>

</div>



<%= render 'form', admin_panel: @admin_panel %>

<%= link_to 'Back', admin_panels_path %>

src/app/views/admin_panels/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Appointment length:</strong>
  <%= @admin_panel.appointment_length %>
</p>

<p>
  <strong>Max appointment count:</strong>
  <%= @admin_panel.max_appointment_count %>
</p>

<p>
  <strong>Booking days:</strong>
  <%= @admin_panel.booking_days %>
</p>

<p>
  <strong>Service time:</strong>
  <%= @admin_panel.service_time %>
</p>

<%= link_to 'Edit', edit_admin_panel_path(@admin_panel) %> |
<%= link_to 'Back', admin_panels_path %>